"""Initial migration

Revision ID: 1e5aca7c8b11
Revises: aee37277d251
Create Date: 2024-08-08 10:27:49.349339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5aca7c8b11'
down_revision = 'aee37277d251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('studentName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studentName', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('student_name')

    # ### end Alembic commands ###
