"""initial migration

Revision ID: aee37277d251
Revises: 
Create Date: 2024-08-07 18:25:36.573692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee37277d251'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=200), nullable=False),
    sa.Column('adm_no', sa.String(length=20), nullable=False),
    sa.Column('education_level', sa.String(length=20), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('form_class', sa.String(length=10), nullable=False),
    sa.Column('fee_balance', sa.Float(), nullable=False),
    sa.Column('parent_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure', sa.String(length=200), nullable=True),
    sa.Column('result_slip', sa.String(length=200), nullable=True),
    sa.Column('birth_cert', sa.String(length=200), nullable=True),
    sa.Column('disable_cert', sa.String(length=200), nullable=True),
    sa.Column('birth_cert_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('father_id_number', sa.String(length=20), nullable=True),
    sa.Column('father_front_id_photo', sa.String(length=200), nullable=True),
    sa.Column('father_back_id_photo', sa.String(length=200), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=False),
    sa.Column('mother_id_number', sa.String(length=20), nullable=False),
    sa.Column('mother_front_id_photo', sa.String(length=200), nullable=True),
    sa.Column('mother_back_id_photo', sa.String(length=200), nullable=True),
    sa.Column('applicant_phone_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bursary_application')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bursary_application',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('studentName', sa.VARCHAR(length=100), nullable=False),
    sa.Column('selectedGender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('admNo', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parent')
    op.drop_table('attachment')
    op.drop_table('student')
    # ### end Alembic commands ###
