"""initial migration

Revision ID: ec9b8431a7f7
Revises: 1e5aca7c8b11
Create Date: 2024-08-08 19:30:54.347870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9b8431a7f7'
down_revision = '1e5aca7c8b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disable_status', sa.String(length=10), nullable=True))
        batch_op.alter_column('disable_cert',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.alter_column('disable_cert',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('disable_status')

    # ### end Alembic commands ###
